#!/usr/bin/env python3
"""Regenerate every placeholder icon, sound effect and music loop and rewrite the ledger.

Usage (from the repository root or anywhere):

    python astra-kingdoms/art/placeholders/generate_all.py            # write assets + ledger
    python astra-kingdoms/art/placeholders/generate_all.py --check    # regenerate to a temp dir
                                                                      # and compare with the ledger

Requires numpy and Pillow (``pip install numpy pillow``). Output:

* ``unity/Assets/Art/Placeholder/Icons/*.png``     40 icons (128 px)
* ``art/placeholders/svg/*.svg``                   their vector sources
* ``unity/Assets/Art/Placeholder/Audio/Sfx/*.wav``   19 one-shots
* ``unity/Assets/Art/Placeholder/Audio/Music/*.wav`` 2 loops
* ``art/ledger/placeholder-assets.ledger.json``    ``AK-ASSET-LEDGER/1`` rows with SHA-256

``--check`` exits 1 when the regenerated bytes differ from the ledger. PNG/WAV bytes depend on the
Pillow/zlib and numpy versions, so a difference on another machine is reported, not hidden; the
committed files and their ledger hashes are the reference.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from akart import icons, ledger, music, sfx  # noqa: E402

AK = HERE.parent.parent  # astra-kingdoms/
UNITY = AK / "unity"
ART_OUT = UNITY / "Assets" / "Art" / "Placeholder"
LEDGER = AK / "art" / "ledger" / "placeholder-assets.ledger.json"


def generate(unity_root: Path, art_out: Path, svg_dir: Path) -> dict:
    ic = icons.generate(art_out / "Icons", svg_dir)
    fx = sfx.generate(art_out / "Audio" / "Sfx")
    mu = music.generate(art_out / "Audio" / "Music")
    return ledger.build(ic, fx, mu, unity_root)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--check", action="store_true", help="regenerate into a temp dir and compare hashes with the ledger")
    args = p.parse_args(argv)
    if args.check:
        committed = json.loads(LEDGER.read_text())
        want = {e["id"]: e["sha256"] for e in committed["entries"]}
        with tempfile.TemporaryDirectory() as tmp:
            troot = Path(tmp) / "unity"
            got = generate(troot, troot / "Assets" / "Art" / "Placeholder", Path(tmp) / "svg")
        have = {e["id"]: e["sha256"] for e in got["entries"]}
        diff = sorted(k for k in set(want) | set(have) if want.get(k) != have.get(k))
        for k in diff:
            print(f"DIFF {k}: ledger {want.get(k)} regenerated {have.get(k)}")
        print("PASS: regenerated bytes match the ledger" if not diff else f"FAIL: {len(diff)} asset(s) differ")
        return 1 if diff else 0
    data = generate(UNITY, ART_OUT, HERE / "svg")
    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    LEDGER.write_text(ledger.dump(data), encoding="ascii", newline="\n")
    print(f"wrote {len(data['entries'])} ledger rows to {LEDGER.relative_to(AK)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
