#!/usr/bin/env python3
"""Generate the AK-TR-1 integer sine lookup table (Combat/TrigTable.Generated.cs).

The rules engine never calls a platform trigonometric function. Instead it reads
sin(k * 0.25 deg) for k = 0..360 (0..90 degrees) from this committed table, stored as
signed Q32.32 raw values (value * 2^32) rounded to nearest with ties to even.
Negative angles and cosines are derived by exact symmetry:
    sin(-a) = -sin(a),  cos(a) = sin(90 deg - |a|).

Values are computed with 80-digit decimal arithmetic (Machin pi + Taylor series), so
the result does not depend on the host's floating-point library. The SHA-256 of the
table bytes (each entry as a little-endian signed 64-bit integer, ascending k) is
emitted as a constant; the rules hash includes these bytes.

Usage (from astra-kingdoms/):
    python3 tools/gen_trig_table.py > src/AstraKingdoms.Rules/Combat/TrigTable.Generated.cs
"""
import hashlib
import struct
from decimal import Decimal, getcontext, ROUND_HALF_EVEN

getcontext().prec = 80

TABLE_VERSION = "AK-TRIG-1"
STEPS_PER_DEGREE = 4
MAX_INDEX = 90 * STEPS_PER_DEGREE  # entries 0..360 inclusive
ONE_RAW = 1 << 32
EPS = Decimal(10) ** -(getcontext().prec - 2)


def arctan_inv(x: int) -> Decimal:
    """arctan(1/x) by its Taylor series."""
    x = Decimal(x)
    x2 = x * x
    term = 1 / x
    total = term
    n = 1
    sign = -1
    while True:
        term /= x2
        delta = term / (2 * n + 1)
        if delta < EPS:
            break
        total += sign * delta
        sign = -sign
        n += 1
    return total


def pi() -> Decimal:
    # Machin: pi/4 = 4 arctan(1/5) - arctan(1/239)
    return 4 * (4 * arctan_inv(5) - arctan_inv(239))


def sin(x: Decimal) -> Decimal:
    term = x
    total = x
    n = 1
    while abs(term) > EPS:
        term = -term * x * x / ((2 * n) * (2 * n + 1))
        total += term
        n += 1
    return total


def main() -> None:
    p = pi()
    raws = []
    for k in range(MAX_INDEX + 1):
        angle = p * k / (180 * STEPS_PER_DEGREE)
        raw = (sin(angle) * ONE_RAW).quantize(Decimal(1), rounding=ROUND_HALF_EVEN)
        raws.append(int(raw))
    assert raws[0] == 0 and raws[-1] == ONE_RAW
    assert all(a < b for a, b in zip(raws, raws[1:]))
    digest = hashlib.sha256(b"".join(struct.pack("<q", r) for r in raws)).hexdigest()

    out = [
        "// <auto-generated>",
        "// Generated by astra-kingdoms/tools/gen_trig_table.py. Do not edit by hand.",
        "// Any change to these values changes combat outcomes and requires a new rules version.",
        "// </auto-generated>",
        "namespace AstraKingdoms.Rules.Combat",
        "{",
        "    public static partial class TrigTable",
        "    {",
        "        /// <summary>Version label of the committed lookup table.</summary>",
        '        public const string Version = "%s";' % TABLE_VERSION,
        "",
        "        /// <summary>SHA-256 of the table bytes (little-endian int64 entries, ascending index).</summary>",
        '        public const string Sha256Hex = "%s";' % digest,
        "",
        "        /// <summary>sin(k x 0.25 deg) for k = 0..%d as Q32.32 raw values.</summary>" % MAX_INDEX,
        "        private static readonly long[] SinQuarterDegreeRaw =",
        "        {",
    ]
    for i in range(0, len(raws), 6):
        out.append("            " + ", ".join("%dL" % r for r in raws[i:i + 6]) + ",")
    out += ["        };", "    }", "}"]
    print("\n".join(out))


if __name__ == "__main__":
    main()
